### ISSUE TITLE
[Ubuntu GNOME] When client is running, shutdown dialog don't appear

### ISSUE THREAD

**Issue by alim0x** [librehat/shadowsocks-qt5#135]
Ubuntu Gnome 15.04
Gnome 3.14

![screenshot from 2015-05-29 17 54 32](https://cloud.githubusercontent.com/assets/4954007/7880466/39a7c400-062c-11e5-86ca-7b165d8d1681.png)

If the qt5 client is running, when I click the third button to shutdown, the confirm dialog will not appear, so I have to shutdown from terminal using command.

![screenshot from 2015-05-29 17 51 19](https://cloud.githubusercontent.com/assets/4954007/7880496/9273f1da-062c-11e5-8b80-5fdf8aab8723.png)

At first I didn't know what cause this problem, but after I close qt5 client, the shutdown dialog works again.

**Comment by librehat** [comment]
The application doesn't interfere with system at all. Honestly, I don't know why would this happen. It sounds more like a distribution issue. It looks similar to #107

**Comment by alim0x** [comment]
曾经在Unity环境下遇到类似bug，那时候是使用Docky 3，在Docky 3开机启动的情况下关机选单出不来，作者给的解释是Unity的api(?)发生了变化，让我向unity反馈，不知道是不是相类似的情况

**Comment by alim0x** [comment]
不管链接是否处于连接状态，均会影响关机菜单弹出，并且qt5窗口显示的时候，点击关闭按钮，不会弹出关机菜单，但是qt5客户端同时也会隐藏/最小化

**Comment by alim0x** [comment]
Find something about similar bug with docky:
https://bugs.launchpad.net/plank/+bug/1242112

Seems like it's about dbus. Hope it will be helpful.

**Comment by librehat** [comment]
Again, I didn't do anything particularly about dbus (execept for notifications). However, it might be something related to Qt and (or) GNOME.

**Comment by alim0x** [comment]
Not find `appIndicatorDE` in `statusdialog.cpp`, find it in `statusnotifier.cpp`, so I add `GNOME` to line 60:

`const QStringList StatusNotifier::appIndicatorDE = QStringList() << "Unity" << "XFCE" << "Pantheon" << "GNOME";`

Then I compiled it. It seems sovled the no icon problem. At first I install it from PPA, icon didn't display in notification. Now I tried compiled version.

Something funny... I installed `ss-qt5` from compiled deb. Start from program list:
![screenshot from 2015-05-30 11 00 32](https://cloud.githubusercontent.com/assets/4954007/7895374/5ef65642-06bb-11e5-942d-b52b9657cc5a.png)

Start `ss-qt5` directly from compiled file:
![screenshot from 2015-05-30 11 03 42](https://cloud.githubusercontent.com/assets/4954007/7895376/9860cfac-06bb-11e5-8bdd-0a884e9f3600.png)
![screenshot from 2015-05-30 11 00 10](https://cloud.githubusercontent.com/assets/4954007/7895377/9b957f60-06bb-11e5-827b-646a97af3290.png)

OK... I have no idea why shutdown dialog can't show... Maybe it GNOME's bug

**Comment by librehat** [comment]
Yes it's `statusnotifier.cpp`. Thanks. So this sovled #66 but the shutdown dialog still won't show, is that right?

**Comment by alim0x** [comment]
Yes. 
But install the compiled deb package, start it from menu have wrong tray icon size. Direct start `ss-qt5` executable program is normal, just as pics above.

**Comment by librehat** [comment]
That's werid. Let's assume it's an upstream bug from GNOME for now.

**Comment by alim0x** [comment]
Have report bug to ubuntu gnome in launchpad.

`syslog`:

I clicked shutdown then clicked cancel in popup dialog. Log shows:

`May 30 21:11:30 hostname gnome-session[1328]: Entering running state`
`May 30 21:11:30 hostname gnome-session[1328]: Gjs-Message: JS LOG: Ignored exception from dbus method: Gio.IOErrorEnum: GDBus.Error:org.freedesktop.DBus.GLib.UnmappedError.GIoErrorQuark.Code19: Operation was cancelled`

When `ss-qt5` is running, I clicked shutdown, `syslog` updated:

`May 30 21:11:30 hostname gnome-session[1328]: Entering running state`
`May 30 21:11:30 hostname gnome-session[1328]: Gjs-Message: JS LOG: Ignored exception from dbus method: Gio.IOErrorEnum: GDBus.Error:org.freedesktop.DBus.GLib.UnmappedError.GIoErrorQuark.Code19: Operation was cancelled`

Hopes upstream will solve it.

**Comment by CzBiX** [comment]
@alim0x Can you provider your bug link in launchpad.
I used Ubuntu 15.04 + Unity, and has the same issue.

**Comment by alim0x** [comment]
@CzBiX https://bugs.launchpad.net/ubuntu-gnome/+bug/1460293
I reported it to Ubuntu GNOME project, you can add "also affects project" or "also affects distribution/package"

**Comment by madjxatw** [comment]
Debian 8 with XFCE has the same issue. Clicking on logout or shutdown button doesn't get any response.

**Comment by librehat** [comment]
Confirmed this is caused by overloaded `closeEvent` #169

**Comment by librehat** [comment]
Should be fixed in latest `master` trunk. Please test, if it persists, re-open this issue.

**Comment by xgdgsc** [comment]
@librehat I tested the master, the bug is fixed, please make a new release.

**Comment by librehat** [comment]
@xgdgsc There are still a few bugs remained to be fixed for `2.4.2`. Please be patient. It should be released before mid September.

**Comment by librehat** [comment]
@xgdgsc Please test the latest `master`, I just pushed another commit.

**Comment by xgdgsc** [comment]
@librehat I tested latest master, it works fine.

**Comment by librehat** [comment]
Thanks.
